name: VSCODETOr
on:
  workflow_dispatch:
jobs:
  alpine-job:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    steps:
      - name: Run command in Alpine
        run: |
          apk update && apk upgrade && apk add curl nano wget naabu httpx nmap
          naabu -p - -host 211.251.236.83 | httpx -status-code -title -tech-detect
