name: Naabu
on:
  workflow_dispatch:
jobs:
  alpine-job:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    steps:
      - name: Run command in Alpine
        run: |
          printf "https://dl-cdn.alpinelinux.org/alpine/v3.23/main\nhttps://dl-cdn.alpinelinux.org/alpine/v3.23/community\nhttps://dl-cdn.alpinelinux.org/alpine/edge/main\nhttps://dl-cdn.alpinelinux.org/alpine/edge/community\nhttps://dl-cdn.alpinelinux.org/alpine/edge/testing" > /etc/apk/repositories
          apk update && apk upgrade && apk add curl nano wget naabu httpx nmap
          naabu -p - -host 61.107.201.0/24 | httpx -status-code -title -tech-detect
